spring:
  application:
    name: Gateway App
  boot:
    admin:
      client:
        # Where the Spring boot admin resides
        url: http://localhost:8100
        # When shut down deregisters from spring boot admin
        auto-deregistration: true
server:
  # Allow for automatic available port allocation
  port: 0
  error:
    # e.g. when an 500 error is displayed will have the underlying error message
    include-message: always
logging:
  file:
    name: gateway-app.log
    max-history: 5
    max-size: 10MB
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

