spring:
  application:
    name: gateway-app
  boot:
    admin:
      client:
        # Where the Spring boot admin resides
        url: http://localhost:8100
        # When shut down deregisters from spring boot admin
        auto-deregistration: true
  cloud:
    #org.springframework.cloud.gateway.config.GatewayProperties
    gateway:
      enabled: true
      routes:
      # View all the routes here:
      # http://localhost:8200/actuator/gateway/routes
      - id: google_route
        uri: http://www.google.com
        predicates:
        - Path=/google
        filters:
          # Send http://localhost:8200/google
          # To http://www.google.com/
          - RewritePath=/google,/
      - id: car_hire_app_route
        # lb - load balancer
        # Will look up car-hire-app service in Eureka and route
        # This to the server and port the car-hire-app instance is running
        uri: lb://car-hire-app
        predicates:
          # e.g. http://localhost:8200/carhire/cars
          # will be routed to
          # http://localhost:52507/carhire/cars
          # If car-hire-app microservice is running at
          # http://localhost:52507
          - Path=/carhire/**
server:
  port: 8200
  error:
    # e.g. when an 500 error is displayed will have the underlying error message
    include-message: always
logging:
  file:
    name: gateway-app.log
    max-history: 5
    max-size: 10MB
management:
  endpoint:
    env:
      # show the values in actuator/env endpoint
      # e.g. http://localhost:8200/actuator/env
      show-values: ALWAYS
    configprops:
      # show the values in actuator/configprops endpoint
      # e.g. http://localhost:8200/actuator/configprops
      show-values: ALWAYS
    health:
      # Note show-details
      show-details: ALWAYS
    shutdown:
      enabled: true
    # show all routes in /actuator/gateway/routes endpoint
    # e.g. http://localhost:8200/actuator/gateway/routes
    # Others
    # GET: /actuator/gateway/globalfilters
    # GET: /actuator/gateway/routefilters
    # POST: /actuator/gateway/refresh
    # GET: /actuator/gateway/routes/{id}
    # POST: /gateway/routes/{id_route_to_create}
    # DELETE: /gateway/routes/{id_route_to_delete}
    gateway:
      enabled: true
  endpoints:
    env:
      # mask these values in actuator/env endpoint
      keys-to-sanitize: password,secret
    configprops:
      # mask these values in actuator/configprops endpoint
      keys-to-sanitize: password,secret
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      # All the GIT info
      mode: full
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}